version: 2.1

parameters:
  markdown_linter:
    type: boolean
    default: false
  build_infrastructure:
    type: boolean
    default: false

orbs:
  terraform: "circleci/terraform@3.1.0"

executors:
  markdown_linter:
    docker:
      - image: davidanson/markdownlint-cli2

commands:
  lint_markdown:
    description: "markdown linting"
    steps:
      - run: markdownlint-cli2 "**/*.md"
  
  lint_terraform:
    description: "installing tf lint and linting"
    steps:
      - run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint

  init_and_plan_terraform:
    description: "terraform init and plan"
    steps:
      - run:
          name: terraform init & plan
          command: |
            terraform -chdir=terraform init -input=false
            terraform -chdir=terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .


jobs:
  lint_documents:
    executor: markdown_linter
    steps:
      - checkout
      - lint_markdown

  lint_init_plan_terraform:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - lint_terraform
      - init_and_plan_terraform

workflows:
  version: 2
  linting_documents:
    when: << pipeline.parameters.markdown_linter >>
    jobs:
      - lint_documents

  build_infrastructure:
    when: << pipeline.parameters.build_infrastructure >>
    jobs:
      - lint_init_plan_terraform