version: 2.1

parameters:
  markdown_linter:
    type: boolean
    default: false
  build_infrastructure:
    type: boolean
    default: false

orbs:
  terraform: "circleci/terraform@3.1.0"

executors:
  markdown_linter:
    docker:
      - image: davidanson/markdownlint-cli2

commands:
  lint_markdown:
    description: "markdown linting"
    steps:
      - run: markdownlint-cli2 "**/*.md"

jobs:
  lint_documents:
    executor: markdown_linter
    steps:
      - checkout
      - lint_markdown

workflows:
  version: 2
  linting_documents:
    when: << pipeline.parameters.markdown_linter >>
    jobs:
      - lint_documents

  build_infrastructure:
    when: << pipeline.parameters.build_infrastructure >>
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate